# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["ENCRYPTFI_API_DATABASE_URL"] %>

development:
  <<: *default
  database: encryptfi_api_development

test:
  <<: *default
  database: encryptfi_api_test

production:
  <<: *default
  database: encryptfi_api_production
